name: Build & Release FlashShapes

on:
  push:
    tags:
      - 'v1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build for Windows
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pygame pyinstaller pillow

      - name: Build executable
        run: pyinstaller flashshapes.spec

      - name: Package .zip
        run: |
          mkdir dist/package
          copy dist\\flashshapes.exe dist\\package\\
          xcopy assets dist\\package\\assets\\ /E /I /Y
          powershell Compress-Archive -Path dist\\package\\* -DestinationPath dist\\flashshapes-windows.zip

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/flashshapes-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    name: Build for macOS
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pygame pyinstaller pillow

      - name: Build .app
        run: pyinstaller flashshapes.spec

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Create .dmg
        run: |
          create-dmg dist/flashshapes.app \
            --volname "FlashShapes" \
            --volicon "assets/icons/icon.icns" \
            dist/

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/flashshapes-macos.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
